# Generated by Django 4.2.7 on 2023-12-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TaskModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=200)),
                ('tasks', models.ManyToManyField(to='TaskModel.add_taskmodel')),
            ],
        ),
    ]
