# Generated by Django 4.2.7 on 2023-12-13 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskCategory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcategory',
            name='tasks',
        ),
    ]
